### PR TITLE
Integrate VP9 coding through cffi & libvpx with tests.

### PR DESCRIPTION
**Pull request by R0NAM1**
Related issue here:
https://github.com/aiortc/aiortc/issues/1180

Seems to be implemented according to the RFC (https://datatracker.ietf.org/doc/html/draft-ietf-payload-vp9-16) and works fine across Firefox & Chrome VP9 implementations.

### CODE REVIEW

**Comment by R0NAM1** [comment]
Only test failing is encoder_large, which also fails with h264 on my machine.

**Comment by R0NAM1** [comment]
@qwert1887 Can you provide the raw SDP codec snippit so I can see all the codecs?
Example:
```
a=rtcp-fb:120 nack
a=rtcp-fb:120 nack pli
a=rtcp-fb:120 ccm fir
a=rtcp-fb:120 goog-remb
a=rtcp-fb:120 transport-cc
a=rtcp-fb:121 nack
a=rtcp-fb:121 nack pli
a=rtcp-fb:121 ccm fir
a=rtcp-fb:121 goog-remb
a=rtcp-fb:121 transport-cc
a=rtcp-fb:126 nack
a=rtcp-fb:126 nack pli
a=rtcp-fb:126 ccm fir
a=rtcp-fb:126 goog-remb
a=rtcp-fb:126 transport-cc
a=rtcp-fb:97 nack
a=rtcp-fb:97 nack pli
a=rtcp-fb:97 ccm fir
a=rtcp-fb:97 goog-remb
a=rtcp-fb:97 transport-cc
a=rtcp-fb:123 nack
a=rtcp-fb:123 nack pli
a=rtcp-fb:123 ccm fir
a=rtcp-fb:123 goog-remb
a=rtcp-fb:123 transport-cc
a=rtcp-fb:122 nack
a=rtcp-fb:122 nack pli
a=rtcp-fb:122 ccm fir
a=rtcp-fb:122 goog-remb
a=rtcp-fb:122 transport-cc
a=rtcp-mux
a=rtcp-rsize
a=rtpmap:120 VP8/90000
a=rtpmap:124 rtx/90000
a=rtpmap:121 VP9/90000
a=rtpmap:125 rtx/90000
a=rtpmap:126 H264/90000
a=rtpmap:127 rtx/90000
a=rtpmap:97 H264/90000
a=rtpmap:98 rtx/90000
a=rtpmap:123 ulpfec/90000
a=rtpmap:122 red/90000
a=rtpmap:119 rtx/90000

a=rtpmap:109 opus/48000/2
a=rtpmap:9 G722/8000/1
a=rtpmap:0 PCMU/8000
a=rtpmap:8 PCMA/8000
```

**Comment by qwert1887** [comment]
@R0NAM1 Thanks a lot, the raw SDP codec snippet as follows:
```
v=0
o=- 3941835936 3941835936 IN IP4 0.0.0.0
s=-
t=0 0
a=group:BUNDLE 0 1
a=msid-semantic:WMS *
m=video 54733 UDP/TLS/RTP/SAVPF 96 97 98 99 100 101 99 99 102 103 106 107
c=IN IP4 192.168.1.166
a=inactive
a=extmap:2 http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time
a=extmap:9 urn:ietf:params:rtp-hdrext:sdes:mid
a=mid:0
a=msid:928e2cab-5cc6-4467-bc9a-3e624fdbe563 43f950d1-919c-492a-a25f-74df7531146e
a=rtcp:9 IN IP4 0.0.0.0
a=rtcp-mux
a=ssrc-group:FID 1507957585 2453533143
a=ssrc:1507957585 cname:fff33e29-b76e-43ef-b2c3-e49440072d89
a=ssrc:2453533143 cname:fff33e29-b76e-43ef-b2c3-e49440072d89
a=rtpmap:96 VP8/90000
a=rtcp-fb:96 nack
a=rtcp-fb:96 nack pli
a=rtcp-fb:96 goog-remb
a=rtpmap:97 rtx/90000
a=fmtp:97 apt=96
a=rtpmap:98 VP9/90000
a=rtcp-fb:98 nack
a=rtcp-fb:98 nack pli
a=rtcp-fb:98 goog-remb
a=rtpmap:99 rtx/90000
a=rtcp-fb:99 nack
a=rtcp-fb:99 nack pli
a=rtcp-fb:99 goog-remb
a=rtcp-fb:99 nack
a=rtcp-fb:99 nack pli
a=rtcp-fb:99 goog-remb
a=fmtp:99 apt=98
a=rtpmap:100 VP9/90000
a=rtcp-fb:100 nack
a=rtcp-fb:100 nack pli
a=rtcp-fb:100 goog-remb
a=rtpmap:101 rtx/90000
a=fmtp:101 apt=100
a=rtpmap:99 VP9/90000
a=rtcp-fb:99 nack
a=rtcp-fb:99 nack pli
a=rtcp-fb:99 goog-remb
a=rtcp-fb:99 nack
a=rtcp-fb:99 nack pli
a=rtcp-fb:99 goog-remb
a=rtpmap:99 VP9/90000
a=rtcp-fb:99 nack
a=rtcp-fb:99 nack pli
a=rtcp-fb:99 goog-remb
a=rtcp-fb:99 nack
a=rtcp-fb:99 nack pli
a=rtcp-fb:99 goog-remb
a=rtpmap:102 H264/90000
a=rtcp-fb:102 nack
a=rtcp-fb:102 nack pli
a=rtcp-fb:102 goog-remb
a=fmtp:102 level-asymmetry-allowed=1;packetization-mode=1;profile-level-id=42001f
a=rtpmap:103 rtx/90000
a=fmtp:103 apt=102
a=rtpmap:106 H264/90000
a=rtcp-fb:106 nack
a=rtcp-fb:106 nack pli
a=rtcp-fb:106 goog-remb
a=fmtp:106 level-asymmetry-allowed=1;packetization-mode=1;profile-level-id=42e01f
a=rtpmap:107 rtx/90000
a=fmtp:107 apt=106
a=candidate:5243000400889625f1cfd57728cff9f3 1 udp 2130706431 192.168.1.166 54733 typ host
a=candidate:580b5f32035da7f14a30ea7a8d826c67 1 udp 2130706431 172.17.0.1 48986 typ host
a=candidate:9cb20c778a0a46a9078ad428e1f0a8e5 1 udp 2130706431 198.18.0.1 35636 typ host
a=end-of-candidates
a=ice-ufrag:wotY
a=ice-pwd:ClmporSEVXe6FldfrU1Mgi
a=fingerprint:sha-256 4D:4B:3D:E7:EF:FA:1B:B9:73:0D:C0:EA:2C:CA:3C:AE:1C:E7:AF:88:57:44:1A:F9:8C:66:44:D5:CD:08:4E:DC
a=setup:active
m=audio 54733 UDP/TLS/RTP/SAVPF 111 0 8
c=IN IP4 192.168.1.166
a=inactive
a=extmap:14 urn:ietf:params:rtp-hdrext:ssrc-audio-level
a=extmap:9 urn:ietf:params:rtp-hdrext:sdes:mid
a=mid:1
a=msid:928e2cab-5cc6-4467-bc9a-3e624fdbe563 41a2fc65-6678-4d90-a648-14d182bd9968
a=rtcp:9 IN IP4 0.0.0.0
a=rtcp-mux
a=ssrc:3059294415 cname:fff33e29-b76e-43ef-b2c3-e49440072d89
a=rtpmap:111 opus/48000/2
a=rtpmap:0 PCMU/8000
a=rtpmap:8 PCMA/8000
a=candidate:5243000400889625f1cfd57728cff9f3 1 udp 2130706431 192.168.1.166 54733 typ host
a=candidate:580b5f32035da7f14a30ea7a8d826c67 1 udp 2130706431 172.17.0.1 48986 typ host
a=candidate:9cb20c778a0a46a9078ad428e1f0a8e5 1 udp 2130706431 198.18.0.1 35636 typ host
a=end-of-candidates
a=ice-ufrag:wotY
a=ice-pwd:ClmporSEVXe6FldfrU1Mgi
a=fingerprint:sha-256 4D:4B:3D:E7:EF:FA:1B:B9:73:0D:C0:EA:2C:CA:3C:AE:1C:E7:AF:88:57:44:1A:F9:8C:66:44:D5:CD:08:4E:DC
a=setup:active
```
There seems to be the conflict caused by the payload type ID 99. By tracking the code, I found that the output `m=video 9 UDP/TLS/RTP/SAVPF 96 97 98 99 100 101 99 99 102 103 106 107` might be related. However, I cannot understand the process that generates the payload type ID. I am new to this,thanks for your patience again.

**Comment by qwert1887** [comment]
image

**Comment by qwert1887** [comment]
It appears that the payload type may be out of range, as defined by DYNAMIC_PAYLOAD_TYPES = range(96, 128) in the file rtp.py. However, I am not certain.
```
def find_common_codecs(
    local_codecs: List[RTCRtpCodecParameters],
    remote_codecs: List[RTCRtpCodecParameters],
) -> List[RTCRtpCodecParameters]:
    common = []
    common_base: Dict[int, RTCRtpCodecParameters] = {}
    for c in remote_codecs:
        # for RTX, check we accepted the base codec
        if is_rtx(c):
            if c.parameters.get("apt") in common_base:
                base = common_base[c.parameters["apt"]]
                if c.clockRate == base.clockRate:
                    common.append(copy.deepcopy(c))
            continue

        # handle other codecs
        for codec in local_codecs:
            if is_codec_compatible(codec, c):
                codec = copy.deepcopy(codec)
                if c.payloadType in rtp.DYNAMIC_PAYLOAD_TYPES:  // Perhaps the payload types 35, 36, 37, and 38 being outside the range(96, 128) leads to the repetition of payload type 99.
                    codec.payloadType = c.payloadType
                codec.rtcpFeedback = list(
                    filter(lambda x: x in c.rtcpFeedback, codec.rtcpFeedback)
                )
                common.append(codec)
                common_base[codec.payloadType] = codec
                break
    return common
```

**Comment by R0NAM1** [comment]
That would make sense, I never touched the payload types so I might have to adjust that for VP9, I can't look right now but I'll update it later.

I also tried it in Chrome and I didn't get any errors but it still wasn't working either so I do believe it's a range issue.

**Comment by R0NAM1** [comment]
Printing local and remote codecs:
```
Local Codecs: [RTCRtpCodecParameters(mimeType='video/VP8', clockRate=90000, channels=None, payloadType=97, rtcpFeedback=[RTCRtcpFeedback(type='nack', parameter=None), RTCRtcpFeedback(type='nack', parameter='pli'), RTCRtcpFeedback(type='goog-remb', parameter=None)], parameters={}), RTCRtpCodecParameters(mimeType='video/rtx', clockRate=90000, channels=None, payloadType=98, rtcpFeedback=[], parameters={'apt': 97}), RTCRtpCodecParameters(mimeType='video/VP9', clockRate=90000, channels=None, payloadType=99, rtcpFeedback=[RTCRtcpFeedback(type='nack', parameter=None), RTCRtcpFeedback(type='nack', parameter='pli'), RTCRtcpFeedback(type='goog-remb', parameter=None)], parameters={}), RTCRtpCodecParameters(mimeType='video/rtx', clockRate=90000, channels=None, payloadType=100, rtcpFeedback=[], parameters={'apt': 99}), RTCRtpCodecParameters(mimeType='video/H264', clockRate=90000, channels=None, payloadType=101, rtcpFeedback=[RTCRtcpFeedback(type='nack', parameter=None), RTCRtcpFeedback(type='nack', parameter='pli'), RTCRtcpFeedback(type='goog-remb', parameter=None)], parameters={'level-asymmetry-allowed': '1', 'packetization-mode': '1', 'profile-level-id': '42001f'}), RTCRtpCodecParameters(mimeType='video/rtx', clockRate=90000, channels=None, payloadType=102, rtcpFeedback=[], parameters={'apt': 101}), RTCRtpCodecParameters(mimeType='video/H264', clockRate=90000, channels=None, payloadType=103, rtcpFeedback=[RTCRtcpFeedback(type='nack', parameter=None), RTCRtcpFeedback(type='nack', parameter='pli'), RTCRtcpFeedback(type='goog-remb', parameter=None)], parameters={'level-asymmetry-allowed': '1', 'packetization-mode': '1', 'profile-level-id': '42e01f'}), RTCRtpCodecParameters(mimeType='video/rtx', clockRate=90000, channels=None, payloadType=104, rtcpFeedback=[], parameters={'apt': 103})]
```

```
Remote Codecs: [RTCRtpCodecParameters(mimeType='video/VP8', clockRate=90000, channels=None, payloadType=120, rtcpFeedback=[RTCRtcpFeedback(type='nack', parameter=None), RTCRtcpFeedback(type='nack', parameter='pli'), RTCRtcpFeedback(type='ccm', parameter='fir'), RTCRtcpFeedback(type='goog-remb', parameter=None), RTCRtcpFeedback(type='transport-cc', parameter=None)], parameters={'max-fs': 12288, 'max-fr': 60}), RTCRtpCodecParameters(mimeType='video/rtx', clockRate=90000, channels=None, payloadType=124, rtcpFeedback=[], parameters={'apt': 120}), RTCRtpCodecParameters(mimeType='video/VP9', clockRate=90000, channels=None, payloadType=121, rtcpFeedback=[RTCRtcpFeedback(type='nack', parameter=None), RTCRtcpFeedback(type='nack', parameter='pli'), RTCRtcpFeedback(type='ccm', parameter='fir'), RTCRtcpFeedback(type='goog-remb', parameter=None), RTCRtcpFeedback(type='transport-cc', parameter=None)], parameters={'max-fs': 12288, 'max-fr': 60}), RTCRtpCodecParameters(mimeType='video/rtx', clockRate=90000, channels=None, payloadType=125, rtcpFeedback=[], parameters={'apt': 121}), RTCRtpCodecParameters(mimeType='video/H264', clockRate=90000, channels=None, payloadType=126, rtcpFeedback=[RTCRtcpFeedback(type='nack', parameter=None), RTCRtcpFeedback(type='nack', parameter='pli'), RTCRtcpFeedback(type='ccm', parameter='fir'), RTCRtcpFeedback(type='goog-remb', parameter=None), RTCRtcpFeedback(type='transport-cc', parameter=None)], parameters={'profile-level-id': '42e01f', 'level-asymmetry-allowed': '1', 'packetization-mode': '1'}), RTCRtpCodecParameters(mimeType='video/rtx', clockRate=90000, channels=None, payloadType=127, rtcpFeedback=[], parameters={'apt': 126}), RTCRtpCodecParameters(mimeType='video/H264', clockRate=90000, channels=None, payloadType=97, rtcpFeedback=[RTCRtcpFeedback(type='nack', parameter=None), RTCRtcpFeedback(type='nack', parameter='pli'), RTCRtcpFeedback(type='ccm', parameter='fir'), RTCRtcpFeedback(type='goog-remb', parameter=None), RTCRtcpFeedback(type='transport-cc', parameter=None)], parameters={'profile-level-id': '42e01f', 'level-asymmetry-allowed': '1'}), RTCRtpCodecParameters(mimeType='video/rtx', clockRate=90000, channels=None, payloadType=98, rtcpFeedback=[], parameters={'apt': 97}), RTCRtpCodecParameters(mimeType='video/ulpfec', clockRate=90000, channels=None, payloadType=123, rtcpFeedback=[RTCRtcpFeedback(type='nack', parameter=None), RTCRtcpFeedback(type='nack', parameter='pli'), RTCRtcpFeedback(type='ccm', parameter='fir'), RTCRtcpFeedback(type='goog-remb', parameter=None), RTCRtcpFeedback(type='transport-cc', parameter=None)], parameters={}), RTCRtpCodecParameters(mimeType='video/red', clockRate=90000, channels=None, payloadType=122, rtcpFeedback=[RTCRtcpFeedback(type='nack', parameter=None), RTCRtcpFeedback(type='nack', parameter='pli'), RTCRtcpFeedback(type='ccm', parameter='fir'), RTCRtcpFeedback(type='goog-remb', parameter=None), RTCRtcpFeedback(type='transport-cc', parameter=None)], parameters={}), RTCRtpCodecParameters(mimeType='video/rtx', clockRate=90000, channels=None, payloadType=119, rtcpFeedback=[], parameters={'apt': 122})]
```

**Comment by R0NAM1** [comment]
Interestingly in my case the failure is in negotiating a video codec, I only get offered audio codecs from AioRTC.
```
v=0
o=- 3941906652 3941906652 IN IP4 0.0.0.0
s=-
t=0 0
a=group:BUNDLE 0 1
a=msid-semantic:WMS *
m=video 9 UDP/TLS/RTP/SAVPF 121
c=IN IP4 0.0.0.0
a=sendonly
a=extmap:3 urn:ietf:params:rtp-hdrext:sdes:mid
a=extmap:4 http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time
a=mid:0
a=msid:405e9345-de7c-479d-a915-32819f4bc764 019d048d-41e7-4c71-9cc9-34e8ace59089
a=rtcp:9 IN IP4 0.0.0.0
a=rtcp-mux
a=ssrc:2857103828 cname:ea62c6c6-c96d-4a3d-8c6b-c0b7450c29ce
a=rtpmap:121 VP9/90000
a=rtcp-fb:121 nack
a=rtcp-fb:121 nack pli
a=rtcp-fb:121 goog-remb
a=ice-ufrag:batJ
a=ice-pwd:H1q6KUxfQI8gnoyClsQGee
a=fingerprint:sha-256 8E:35:88:C4:F8:B6:1F:87:70:FA:FF:30:BB:D4:5E:0E:1D:F7:75:8D:DE:10:E7:BB:6E:AB:3A:A9:C2:8A:F0:EB
a=setup:active
m=audio 9 UDP/TLS/RTP/SAVPF 109 0 8
c=IN IP4 0.0.0.0
a=inactive
a=extmap:1 urn:ietf:params:rtp-hdrext:ssrc-audio-level
a=extmap:3 urn:ietf:params:rtp-hdrext:sdes:mid
a=mid:1
a=msid:405e9345-de7c-479d-a915-32819f4bc764 8dd0bddb-1ae3-4a53-aed1-6066b492df7e
a=rtcp:9 IN IP4 0.0.0.0
a=rtcp-mux
a=ssrc:3120264515 cname:ea62c6c6-c96d-4a3d-8c6b-c0b7450c29ce
a=rtpmap:109 opus/48000/2
a=rtpmap:0 PCMU/8000
a=rtpmap:8 PCMA/8000
a=ice-ufrag:batJ
a=ice-pwd:H1q6KUxfQI8gnoyClsQGee
a=fingerprint:sha-256 8E:35:88:C4:F8:B6:1F:87:70:FA:FF:30:BB:D4:5E:0E:1D:F7:75:8D:DE:10:E7:BB:6E:AB:3A:A9:C2:8A:F0:EB
a=setup:active
```

**Comment by qwert1887** [comment]
> It appears that the payload type may be out of range, as defined by DYNAMIC_PAYLOAD_TYPES = range(96, 128) in the file rtp.py. However, I am not certain.
> 
> ```
> def find_common_codecs(
>     local_codecs: List[RTCRtpCodecParameters],
>     remote_codecs: List[RTCRtpCodecParameters],
> ) -> List[RTCRtpCodecParameters]:
>     common = []
>     common_base: Dict[int, RTCRtpCodecParameters] = {}
>     for c in remote_codecs:
>         # for RTX, check we accepted the base codec
>         if is_rtx(c):
>             if c.parameters.get("apt") in common_base:
>                 base = common_base[c.parameters["apt"]]
>                 if c.clockRate == base.clockRate:
>                     common.append(copy.deepcopy(c))
>             continue
> 
>         # handle other codecs
>         for codec in local_codecs:
>             if is_codec_compatible(codec, c):
>                 codec = copy.deepcopy(codec)
>                 if c.payloadType in rtp.DYNAMIC_PAYLOAD_TYPES:  // Perhaps the payload types 35, 36, 37, and 38 being outside the range(96, 128) leads to the repetition of payload type 99.
>                     codec.payloadType = c.payloadType
>                 else:
>                     print(f"\n[PRINT] remote codec payloadType {c.payloadType} is not in {rtp.DYNAMIC_PAYLOAD_TYPES}")
>                 codec.rtcpFeedback = list(
>                     filter(lambda x: x in c.rtcpFeedback, codec.rtcpFeedback)
>                 )
>                 common.append(codec)
>                 common_base[codec.payloadType] = codec
>                 break
>     return common
> ```


I am confused about where the 35 and the 37 are generated.
[PRINT] remote codec payloadType 35 is not in range(96, 128)
[PRINT] remote codec payloadType 37 is not in range(96, 128)

**Comment by R0NAM1** [comment]
Have time to mess with this today, so far I've found that for some reason I'm able to get two or three frames of VP9 out before they stop being updated on the client despite RTP Packets still being sent.

Comparing in a diff checker the only things changed is VP8 to VP9, 120 to 121 and all other source & secret info as normal...

It also stops consistantly at the same time, we might have two different issues here- 

1. An SDP Mapping issue- Since I'm not experiencing this personally and can't replicate it or find anything in the code I can't do anything at the moment.
2. Some odd encoding? Issue with the Webcam Example for me, I've replaced it with a native VP9 encoded video and thats how I know it stops in the same spot.

So I'll work on 2 but I have no ideas for 1

**Comment by R0NAM1** [comment]
From Chrome --enabl
```
[2068743:11:1206/163054.881314:INFO:peer_connection.cc(2385)] Changing to ICE completed state because all transports are complete.
[2068743:11:1206/163054.881390:INFO:peer_connection.cc(1909)] Changing IceConnectionState 1 => 2
[2068743:11:1206/163054.881448:INFO:peer_connection.cc(1909)] Changing IceConnectionState 2 => 3
[2068743:11:1206/163054.881508:INFO:peer_connection.cc(1928)] Changing standardized IceConnectionState 2 => 3
[2068743:12:1206/163054.882620:INFO:srtp_transport.cc(230)] SRTP activated with negotiated parameters: send crypto_suite 1 recv crypto_suite 1
[2068743:12:1206/163054.882660:INFO:channel.cc(554)] Channel writable ({mid: 0, media_type: video}) for the first time
[2068743:12:1206/163054.882695:INFO:channel.cc(554)] Channel writable ({mid: 1, media_type: audio}) for the first time
[2068743:12:1206/163054.882770:VERBOSE1:webrtc_video_engine.cc(2808)] SetReceive: true
[2068743:12:1206/163054.882807:VERBOSE1:webrtc_video_engine.cc(1419)] SetSend: false
[2068743:12:1206/163054.882840:INFO:channel.cc(999)] Changing video state, recv=1 send=0 for {mid: 0, media_type: video}
[2068743:12:1206/163054.882872:INFO:channel.cc(859)] Changing voice state, recv=1 send=0 for {mid: 1, media_type: audio}
[2068743:12:1206/163054.908975:INFO:receive_side_congestion_controller.cc(54)] WrappingBitrateEstimator: Switching to absolute send time RBE.
[2068743:12:1206/163054.909073:INFO:aimd_rate_control.cc(87)] Using aimd rate control with back off factor 0.85
[2068743:12:1206/163054.909117:INFO:remote_bitrate_estimator_abs_send_time.cc(95)] RemoteBitrateEstimatorAbsSendTime: Instantiating.
[2068743:12:1206/163054.909183:INFO:rtp_video_stream_receiver2.cc(1331)] Packet received on SSRC: 1876263908 with payload type: 98, timestamp: 3734675864, sequence number: 32640, arrival time: 1984533116844 us, abs send time: 16491125
[2068743:3:1206/163054.910491:INFO:generic_decoder.cc(278)] Decoder implementation: DecoderInfo { prefers_late_decoding = implementation_name = 'libvpx', is_hardware_accelerated = false }
[2068743:1:1206/163054.914492:VERBOSE1:webrtc_logging.cc(35)] WMPMS::SetReadyState => (state=HaveNothing) [delegate_id=1]
[2068743:1:1206/163054.914635:VERBOSE1:webrtc_logging.cc(35)] WMPMS::SetReadyState => (state=HaveMetadata) [delegate_id=1]
[2068743:1:1206/163054.914813:VERBOSE1:webrtc_logging.cc(35)] WMPMS::SetVolume({volume=1.00}) [delegate_id=1]
[2068743:1:1206/163054.914862:VERBOSE1:webrtc_logging.cc(35)] WMPMS::Play() [delegate_id=1]
[2068743:12:1206/163054.917098:VERBOSE1:connection.cc(922)] Conn[237f800:0:Net[any:0.0.0.x/0:Wildcard:id=0]:4SDjz/4K:1:0:host:udp:ac69a589-5c7c-4526-a796-b8a30abe1a6a.local:39430->62rbIot7:1:2130706431:host:udp:10.42.0.x:55604|CRWS|S|0|0|9079290933605826558|2]: UpdateState(), ms since last received response=55, ms since last received data=9, rtt=100, pings_since_last_response=
[2068743:12:1206/163054.964153:VERBOSE1:connection.cc(922)] Conn[2382800:0:Net[any:0.0.0.x/0:Wildcard:id=0]:4SDjz/4K:1:0:host:udp:ac69a589-5c7c-4526-a796-b8a30abe1a6a.local:39430->NBGbktF6:1:2130706431:host:udp:192.168.122.x:37334|C-xW|-|0|0|9079290933605826558|-]: UpdateState(), ms since last received response=1984533125, ms since last received data=1984533125, rtt=6000, pings_since_last_response=
[2068743:12:1206/163054.964207:VERBOSE1:connection.cc(922)] Conn[2bbc000:0:Net[any:0.0.0.x/0:Wildcard:id=0]:4SDjz/4K:1:0:host:udp:ac69a589-5c7c-4526-a796-b8a30abe1a6a.local:39430->rYcXHiKD:1:1694498815:srflx:udp:98.97.34.x:15085|C-xW|-|0|0|7277816997763628543|-]: UpdateState(), ms since last received response=1984533125, ms since last received data=1984533125, rtt=6000, pings_since_last_response=
[2068743:12:1206/163054.964254:VERBOSE1:connection.cc(922)] Conn[2bbd800:0:Net[any:0.0.0.x/0:Wildcard:id=0]:4SDjz/4K:1:0:host:udp:ac69a589-5c7c-4526-a796-b8a30abe1a6a.local:39430->El/Bb19c:1:1694498815:srflx:udp:98.97.34.x:53318|C-xW|-|0|0|7277816997763628543|-]: UpdateState(), ms since last received response=1984533125, ms since last received data=1984533125, rtt=6000, pings_since_last_response=
[2068743:12:1206/163054.964327:VERBOSE1:connection.cc(1015)] Conn[237f800:0:Net[any:0.0.0.x/0:Wildcard:id=0]:4SDjz/4K:1:0:host:udp:ac69a589-5c7c-4526-a796-b8a30abe1a6a.local:39430->62rbIot7:1:2130706431:host:udp:10.42.0.x:55604|CRWS|S|0|0|9079290933605826558|2]: Sending STUN ping, id=2f3839307851516b4f495537, nomination=0
[2068743:12:1206/163054.964396:VERBOSE1:connection.cc(1534)] Conn[237f800:0:Net[any:0.0.0.x/0:Wildcard:id=0]:4SDjz/4K:1:0:host:udp:ac69a589-5c7c-4526-a796-b8a30abe1a6a.local:39430->62rbIot7:1:2130706431:host:udp:10.42.0.x:55604|CRWS|S|0|0|9079290933605826558|2]: Sent STUN BINDING request, id=2f3839307851516b4f495537, use_candidate=1, nomination=0
[2068743:3:1206/163054.964548:WARNING:libvpx_vp9_decoder.cc(216)] Failed to parse VP9 header from key-frame.
[2068743:12:1206/163054.964556:INFO:remote_bitrate_estimator_abs_send_time.cc(275)] Probe packet received: send time=62956 ms, recv time=1984533164 ms, send delta=-1 ms, recv delta=-1 ms.
[2068743:12:1206/163054.964748:VERBOSE1:connection.cc(1416)] Conn[237f800:0:Net[any:0.0.0.x/0:Wildcard:id=0]:4SDjz/4K:1:0:host:udp:ac69a589-5c7c-4526-a796-b8a30abe1a6a.local:39430->62rbIot7:1:2130706431:host:udp:10.42.0.x:55604|CRWI|S|0|0|9079290933605826558|2]: Received STUN BINDING response, id=2f3839307851516b4f495537, code=0, rtt=0, pings_since_last_response=2f3839307851516b4f495537 
[2068743:12:1206/163054.964804:VERBOSE1:connection.cc(346)] Conn[237f800:0:Net[any:0.0.0.x/0:Wildcard:id=0]:4SDjz/4K:1:0:host:udp:ac69a589-5c7c-4526-a796-b8a30abe1a6a.local:39430->62rbIot7:1:2130706431:host:udp:10.42.0.x:55604|CRWS|S|0|0|9079290933605826558|2]: set_state
[2068743:3:1206/163054.979605:WARNING:libvpx_vp9_decoder.cc(216)] Failed to parse VP9 header from key-frame.
[2068743:3:1206/163055.010875:WARNING:libvpx_vp9_decoder.cc(216)] Failed to parse VP9 header from key-frame.
[2068743:3:1206/163055.026477:WARNING:libvpx_vp9_decoder.cc(216)] Failed to parse VP9 header from key-frame.
[2068743:12:1206/163055.026487:VERBOSE1:connection.cc(922)] Conn[237f800:0:Net[any:0.0.0.x/0:Wildcard:id=0]:4SDjz/4K:1:0:host:udp:ac69a589-5c7c-4526-a796-b8a30abe1a6a.local:39430->62rbIot7:1:2130706431:host:udp:10.42.0.x:55604|CRWS|S|0|0|9079290933605826558|1]: UpdateState(), ms since last received response=62, ms since last received data=4, rtt=100, pings_since_last_response=
[2068743:12:1206/163055.026578:VERBOSE1:connection.cc(922)] Conn[2382800:0:Net[any:0.0.0.x/0:Wildcard:id=0]:4SDjz/4K:1:0:host:udp:ac69a589-5c7c-4526-a796-b8a30abe1a6a.local:39430->NBGbktF6:1:2130706431:host:udp:192.168.122.x:37334|C-xW|-|0|0|9079290933605826558|-]: UpdateState(), ms since last received response=1984533234, ms since last received data=1984533234, rtt=6000, pings_since_last_response=
[2068743:12:1206/163055.026634:VERBOSE1:connection.cc(922)] Conn[2bbc000:0:Net[any:0.0.0.x/0:Wildcard:id=0]:4SDjz/4K:1:0:host:udp:ac69a589-5c7c-4526-a796-b8a30abe1a6a.local:39430->rYcXHiKD:1:1694498815:srflx:udp:98.97.34.x:15085|C-xW|-|0|0|7277816997763628543|-]: UpdateState(), ms since last received response=1984533234, ms since last received data=1984533234, rtt=6000, pings_since_last_response=
[2068743:12:1206/163055.026685:VERBOSE1:connection.cc(922)] Conn[2bbd800:0:Net[any:0.0.0.x/0:Wildcard:id=0]:4SDjz/4K:1:0:host:udp:ac69a589-5c7c-4526-a796-b8a30abe1a6a.local:39430->El/Bb19c:1:1694498815:srflx:udp:98.97.34.x:53318|C-xW|-|0|0|7277816997763628543|-]: UpdateState(), ms since last received response=1984533234, ms since last received data=1984533234, rtt=6000, pings_since_last_response=
[2068743:12:1206/163055.026749:VERBOSE1:connection.cc(1015)] Conn[237f800:0:Net[any:0.0.0.x/0:Wildcard:id=0]:4SDjz/4K:1:0:host:udp:ac69a589-5c7c-4526-a796-b8a30abe1a6a.local:39430->62rbIot7:1:2130706431:host:udp:10.42.0.x:55604|CRWS|S|0|0|9079290933605826558|1]: Sending STUN ping, id=7242646f686965594b595a6b, nomination=0
```


Notice 
```
WARNING:libvpx_vp9_decoder.cc(216)] Failed to parse VP9 header from key-frame.
```

That's very likely my encoder header implementation, probably those Scalability Structures- Arrgggg...

I'll close this for now and continue in my original Issue thread.

**Comment by qwert1887** [comment]
I apologize, but I have limited time to explore this at the moment as I am currently engaged in other tasks.

**Pull request closed without merging**
