### PR TITLE
[Logging] change logger convention to include package name

### PR DESCRIPTION
**Pull request by Laityned**
Update setup.py and gitignore to be compatible with development environments and installments required for coverage tests

Update loggers to follow standard convention as specified in issue #446

### CODE REVIEW

**Comment by jlaine** [comment]
Please keep changes to .gitignore and setup.py out of this PR, they don't seem related to the topic of the PR

**Comment by jlaine** [comment]
You missed a couple of loggers, I fixed this is 5b06316c17a5dfe5a34e6f1bf0a6710755c171c5

**Comment by jlaine** [comment]
Thanks for the patch, it's much tidier like this. Feel free to submit an equivalent PR against `aioice` which has the same problem :)

**Comment by Laityned** [comment]
No problem, my apologizes for missing some loggers. I submitted a similar  one to aioice

**Pull request merged**
