### PR TITLE
Fix crc32c import warning on rtcsctptransport

### PR DESCRIPTION
**Pull request by fabriciopk**
The current crc32 method used by rtcsctptransport has a deprecation warning.

>>> from crc32c import crc32
>>> crc32(b"bla")
__main__:1: DeprecationWarning: crc32c.crc32 will be eventually removed, use crc32c.crc32c instead
3380944313

### CODE REVIEW

**Comment by jlaine** [comment]
What version of crc32c introduced this name change? I'm thinking we need to update setup.py to reflect the minimum version of crc32c featuring the new name.

**Review by duc811997 — APPROVED** [review]

**Review by duc811997 — APPROVED** [review]

**Comment by duc811997** [comment]
> The current crc32 method used by rtcsctptransport has a deprecation warning.
> 
> 
> 
> >>> from crc32c import crc32
> 
> >>> crc32(b"bla")
> 
> __main__:1: DeprecationWarning: crc32c.crc32 will be eventually removed, use crc32c.crc32c instead
> 
> 3380944313

**Comment by duc811997** [comment]
> > The current crc32 method used by rtcsctptransport has a deprecation warning.
> > 
> > 
> > 
> > >>> from crc32c import crc32
> > 
> > >>> crc32(b"bla")
> > 
> > __main__:1: DeprecationWarning: crc32c.crc32 will be eventually removed, use crc32c.crc32c instead
> > 
> > 3380944313
> 
>

**Review by duc811997 — APPROVED** [review]

**Comment by duc811997** [comment]
> # [Codecov](https://codecov.io/gh/aiortc/aiortc/pull/438?src=pr&el=h1) Report
> > Merging [#438](https://codecov.io/gh/aiortc/aiortc/pull/438?src=pr&el=desc) (be74988) into [main](https://codecov.io/gh/aiortc/aiortc/commit/7a74e5342610595404b654e75170f813216130ea?el=desc) (7a74e53) will **increase** coverage by `0.12%`.
> > The diff coverage is `100.00%`.
> 
> [Impacted file tree graph](https://codecov.io/gh/aiortc/aiortc/pull/438?src=pr&el=tree)
> 
> ```diff
> @@             Coverage Diff             @@
> ##             main      #438      +/-   ##
> ===========================================
> + Coverage   99.87%   100.00%   +0.12%     
> ===========================================
>   Files          31        31              
>   Lines        5393      5492      +99     
> ===========================================
> + Hits         5386      5492     +106     
> + Misses          7         0       -7     
> ```
> 
> 
> | [Impacted Files](https://codecov.io/gh/aiortc/aiortc/pull/438?src=pr&el=tree) | Coverage Δ | |
> |---|---|---|
> | [src/aiortc/rtcsctptransport.py](https://codecov.io/gh/aiortc/aiortc/pull/438/diff?src=pr&el=tree#diff-c3JjL2Fpb3J0Yy9ydGNzY3RwdHJhbnNwb3J0LnB5) | `100.00% <100.00%> (ø)` | |
> | [src/aiortc/rtp.py](https://codecov.io/gh/aiortc/aiortc/pull/438/diff?src=pr&el=tree#diff-c3JjL2Fpb3J0Yy9ydHAucHk=) | `100.00% <0.00%> (ø)` | |
> | [src/aiortc/sdp.py](https://codecov.io/gh/aiortc/aiortc/pull/438/diff?src=pr&el=tree#diff-c3JjL2Fpb3J0Yy9zZHAucHk=) | `100.00% <0.00%> (ø)` | |
> | [src/aiortc/rate.py](https://codecov.io/gh/aiortc/aiortc/pull/438/diff?src=pr&el=tree#diff-c3JjL2Fpb3J0Yy9yYXRlLnB5) | `100.00% <0.00%> (ø)` | |
> | [src/aiortc/stats.py](https://codecov.io/gh/aiortc/aiortc/pull/438/diff?src=pr&el=tree#diff-c3JjL2Fpb3J0Yy9zdGF0cy5weQ==) | `100.00% <0.00%> (ø)` | |
> | [src/aiortc/codecs/vpx.py](https://codecov.io/gh/aiortc/aiortc/pull/438/diff?src=pr&el=tree#diff-c3JjL2Fpb3J0Yy9jb2RlY3MvdnB4LnB5) | `100.00% <0.00%> (ø)` | |
> | [src/aiortc/codecs/g711.py](https://codecov.io/gh/aiortc/aiortc/pull/438/diff?src=pr&el=tree#diff-c3JjL2Fpb3J0Yy9jb2RlY3MvZzcxMS5weQ==) | `100.00% <0.00%> (ø)` | |
> | [src/aiortc/codecs/opus.py](https://codecov.io/gh/aiortc/aiortc/pull/438/diff?src=pr&el=tree#diff-c3JjL2Fpb3J0Yy9jb2RlY3Mvb3B1cy5weQ==) | `100.00% <0.00%> (ø)` | |
> | [src/aiortc/jitterbuffer.py](https://codecov.io/gh/aiortc/aiortc/pull/438/diff?src=pr&el=tree#diff-c3JjL2Fpb3J0Yy9qaXR0ZXJidWZmZXIucHk=) | `100.00% <0.00%> (ø)` | |
> | [src/aiortc/mediastreams.py](https://codecov.io/gh/aiortc/aiortc/pull/438/diff?src=pr&el=tree#diff-c3JjL2Fpb3J0Yy9tZWRpYXN0cmVhbXMucHk=) | `100.00% <0.00%> (ø)` | |
> | ... and [13 more](https://codecov.io/gh/aiortc/aiortc/pull/438/diff?src=pr&el=tree-more) | |
> 
> ------
> 
> [Continue to review full report at Codecov](https://codecov.io/gh/aiortc/aiortc/pull/438?src=pr&el=continue).
> > **Legend** - [Click here to learn more](https://docs.codecov.io/docs/codecov-delta)
> > `Δ = absolute <relative> (impact)`, `ø = not affected`, `? = missing data`
> > Powered by [Codecov](https://codecov.io/gh/aiortc/aiortc/pull/438?src=pr&el=footer). Last update [7a74e53...be74988](https://codecov.io/gh/aiortc/aiortc/pull/438?src=pr&el=lastupdated). Read the [comment docs](https://docs.codecov.io/docs/pull-request-comments).
>

**Comment by duc811997** [comment]
stubs/crc32c.pyi

**Review by duc811997 — APPROVED** [review]

**Comment by jlaine** [comment]
This is superseeded by #456

**Pull request closed without merging**
