### PR TITLE
[data channels] look for the lowest available stream id

### PR DESCRIPTION
**Pull request by jlaine**
Fixes: #256

### CODE REVIEW

**Comment by stalkerg** [comment]
Thanks, it's should be enough. I have a very similar code in the browser code now. 
Anyway, you can't check the maximum amount of channels from the "server". 
It will be great only add in documentation somewhere some warnings about current browsers limitations because behaviour then you try to open more channels from the server very odd.  (without any exceptions and etc)

**Comment by lgrahl** [comment]
> Anyway, you can't check the maximum amount of channels from the "server".

Sure you can. It's the minimum of the negotiated amount of incoming and outgoing streams. See `maxChannels` in the WebRTC spec.

**Comment by stalkerg** [comment]
@lgrahl I mostly talking about aiortc. Also even on browser-side this param announcing in Chrome only. 
But if this param exist and browsers are using it, I suppose it's great.

**Comment by jlaine** [comment]
> Sure you can. It's the minimum of the negotiated amount of incoming and outgoing streams. See `maxChannels` in the WebRTC spec. It should be easy to expose that field. slightly_smiling_face

What I'm not finding in the specs is the expected behaviour if additional streams are negotiated using a RE-CONFIG chunk : does maxChannels get raised to reflect the additional streams?

**Comment by lgrahl** [comment]
> What I'm not finding in the specs is the expected behaviour if additional streams are negotiated using a RE-CONFIG chunk : does maxChannels get raised to reflect the additional streams?

While renegotiation is part of this extension spec of SCTP, it is not mandatory for WebRTC data channels. But, sure, the answer would be yes.

**Pull request merged**
