### PR TITLE
Support alsa hardware output in MediaRecorder

### PR DESCRIPTION
**Pull request by seler**
This change allows for MediaRecorder to stream tracks to alsa hardware output.

### CODE REVIEW

**Comment by jlaine** [comment]
This is an interesting change, do you have a link to a document which shows that this is always the right sample format for alsa?

**Comment by seler** [comment]
Alsa is pcm, same as wav.

**Comment by seler** [comment]
> This is an interesting change, do you have a link to a document which shows that this is always the right sample format for alsa?

Alsa is pcm, same as wav.

**Comment by seler** [comment]
Is it even possible to write a test for alsa without the hardware? Any suggestions?

**Comment by jlaine** [comment]
Does ALSA have a concept of a "null device" we can maybe leverage?

Otherwise I shouldn't sweat it, if it works for you and doesn't trigger a regression, I'll for once have to live without a test :)

**Comment by seler** [comment]
> Does ALSA have a concept of a "null device" we can maybe leverage? In any case I expect the test would need to be disable on any platform that isn't Linux.

```
$ arecord -L
null
    Discard all samples (playback) or generate zero samples (capture)
```
It does. Except you still need alsa set up on server. More info on [alsa wiki](https://www.alsa-project.org/main/index.php/Matrix:Module-dummy)

**Pull request merged**
