### PR TITLE
Use unique ids for audio and video header extensions

### LINKED ISSUE #745: 'Absolute Send Time' WebRTC extension bug
Hi,
I get the following warning upon the successfull connection of the two peers (but in fact it is an error since it prevent completely the tracks to be sent and received):
```
[WARNING][2022-06-28 13:00:29,863](72026)aiortc.rtcdtlstransport: RTCDtlsTransport(client) Traceback (most recent call last):
  File "/home/bob/ws/modules/streaming-module/venv/lib/python3.8/site-packages/aiortc/rtcdtlstransport.py", line 531, in __run
    await self._recv_next()
  File "/home/bob/ws/modules/streaming-module/venv/lib/python3.8/site-packages/aiortc/rtcdtlstransport.py", line 630, in _recv_next
    await self._handle_rtp_data(data, arrival_time_ms=arrival_time_ms)
  File "/home/bob/ws/modules/streaming-module/venv/lib/python3.8/site-packages/aiortc/rtcdtlstransport.py", line 575, in _handle_rtp_data
    packet = RtpPacket.parse(data, self._rtp_header_extensions_map)
  File "/home/bob/ws/modules/streaming-module/venv/lib/python3.8/site-packages/aiortc/rtp.py", line 710, in parse
    packet.extensions = extensions_map.get(extension_profile, extension_value)
  File "/home/bob/ws/modules/streaming-module/venv/lib/python3.8/site-packages/aiortc/rtp.py", line 89, in get
    values.abs_send_time = unpack("!L", b"\00" + x_value)[0]
struct.error: unpack requires a buffer of 4 bytes
```

I investigated a bit and I understood that is caused by the RTP extension "Absolute Send Time" ([https://webrtc.googlesource.com/src/+/refs/heads/main/docs/native-code/rtp-hdrext/abs-send-time](https://webrtc.googlesource.com/src/+/refs/heads/main/docs/native-code/rtp-hdrext/abs-send-time))
In the specification it is written that this extension is 4 bytes long, but the code in aiortc/rtp.py seems to ignore this and try to get the extension value as for any other extension. Then this value is unpacked but being too short an exception from the struct package is thrown.
You think all this I supposed is right? 
I can try patching it and sending you a first fix.
Have a great day

### PR DESCRIPTION
**Pull request by juberti**
Fixes #745 
Problem identified by @eerimoq

### CODE REVIEW

**Comment by juberti** [comment]
@jlaine can we merge this?

**Comment by eerimoq** [comment]
Please =)

**Comment by fippo** [comment]
This is particularly important since [M116](https://groups.google.com/g/discuss-webrtc/c/bEsO8Lz7psE/m/wVDwcuhIAAAJ) got released earlier this month which includes stricter checking for collisions?

**Comment by weishengtoh** [comment]
please integrate this. thank you.

**Comment by david-goldb** [comment]
Any updates here? :)

**Comment by juberti** [comment]
@lgrahl , do you have a way of directly getting in touch with Jeremy? Happy to do whatever is needed to get this integrated and a new release cut.

**Comment by lgrahl** [comment]
I'm currently trying to reach him. Will keep you posted.

**Comment by lgrahl** [comment]
> I'm currently trying to reach him. Will keep you posted.

Unfortunately without any luck so far. Here's my plan:

For a transitional period, I would curate merging vital pull requests (such as this one) to the best of my abilities and create a new repo on PyPI. Any help is appreciated here, be it reviewing pull requests, reaching Jeremy via other channels, or providing further documentation, e.g. steps necessary to build and push to PyPI.

If Jeremy doesn't respond until the end of the year, I will reach out to contributors and try to sort out the long-term maintenance.

**Review by rprata — APPROVED** [review]

**Comment by lgrahl** [comment]
Before I merge: Can you add a short test that fails when there is overlap of these header extension IDs? That's probably better than a warning.

**Comment by jlaine** [comment]
This does look like good PR to merge. I am however a little confused as I don't remember if we do *actually* negotiate the extension IDs during the SDP exchange?

For some context: I took a fairly extended leave of absence from my opensource projects as they were proving a net negative for me. I am progressively trying to get back on top of things, and would welcome active co-maintainers to future-proof these projects.

@lgrahl on a practical note: upload to PyPI is automated. Once you apply a tag, CI will take care of the upload to PyPI provided the tests pass.

**Comment by jlaine** [comment]
I'm going to merge this as-is, but I think we do need to review whether extension header IDs need to be negotiated.

**Comment by fippo** [comment]
The subject of whether such ids (or payload types) are negotiated or declarative is a long standing issue. Welcome back!

**Pull request merged**
